export const operations = [
  {id: 1, value: 'C'},
  {id: 2, value: '7'},
  {id: 3, value: '8'},
  {id: 4, value: '9'},
  {id: 5, value: '*'},
  {id: 6, value: '-'},
  {id: 7, value: '4'},
  {id: 8, value: '5'},
  {id: 9, value: '6'},
  {id: 10, value: '/'},
  {id: 11, value: '+'},
  {id: 12, value: '1'},
  {id: 13, value: '2'},
  {id: 14, value: '3'},
  {id: 15, value: '='},
  {id: 16, value: '.'},
  {id: 17, value: '('},
  {id: 18, value: '0'},
  {id: 19, value: ')'},
  {id: 20, value: 'CE'},
];